from __future__ import annotations

import importlib.metadata
import tomllib
from pathlib import Path

import pytest

from scripts import check_toolchain

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def test_repository_toolchain_manifest_matches_project() -> None:
    tools = check_toolchain.validate(PROJECT_ROOT, verify_installed=False)
    locked = check_toolchain.parse_lock(PROJECT_ROOT / "requirements/toolchain.lock", tools)

    assert tools["editables"] == "0.5"
    assert tools["hatchling"] == "1.31.0"
    assert tools["pytest"] == "9.1.1"
    assert tools["twine"] == "6.2.0"
    assert tools["uv"] == "0.11.21"
    assert len(locked) == 57
    assert locked["editables"] == {"0.5"}
    assert locked["pytest"] == {"9.1.1"}
    lock_text = (PROJECT_ROOT / "requirements/toolchain.lock").read_text(encoding="utf-8")
    assert "sys_platform == 'linux'" in lock_text
    assert "sys_platform == 'win32'" in lock_text
    assert "python_full_version < '3.12'" in lock_text
    project = tomllib.loads((PROJECT_ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    assert project["project"]["dependencies"] == []


def test_tool_invoking_workflows_use_the_hash_lock_and_release_prepares_assets_first() -> None:
    workflow_root = PROJECT_ROOT / ".github/workflows"
    locked_workflows = (
        "benchmark.yml",
        "ci.yml",
        "mutation-testing.yml",
        "published-artifacts.yml",
        "release.yml",
    )
    for name in locked_workflows:
        workflow = (workflow_root / name).read_text(encoding="utf-8")
        assert "pip install --require-hashes --only-binary=:all:" in workflow
        assert "check_toolchain.py" in workflow
        assert "pip install --upgrade" not in workflow

    for name in ("benchmark.yml", "ci.yml", "mutation-testing.yml", "release.yml"):
        workflow = (workflow_root / name).read_text(encoding="utf-8")
        assert "pip install --no-build-isolation --no-deps -e ." in workflow

    ci = (workflow_root / "ci.yml").read_text(encoding="utf-8")
    release = (workflow_root / "release.yml").read_text(encoding="utf-8")
    assert ci.count("--runner-label ubuntu-latest") == ci.count(
        "python -m scripts.reproducible_builds"
    )
    assert release.count("--runner-label ubuntu-24.04") == release.count(
        "python -m scripts.reproducible_builds"
    )
    assert release.index("Verify the complete pre-publication asset set") < release.index(
        "Publish to PyPI"
    )
    assert "/build-metadata/" in (PROJECT_ROOT / ".gitignore").read_text(encoding="utf-8")


def test_manifest_rejects_ranges_duplicates_and_unknown_tools(tmp_path: Path) -> None:
    manifest = tmp_path / "toolchain.txt"
    manifest.write_text(
        "# uv pip compile requirements/toolchain.txt --universal --generate-hashes "
        "--python-version 3.11 --output-file requirements/toolchain.lock\n"
        "pytest>=9\npytest==9.1.1\nunknown==1\n",
        encoding="utf-8",
    )

    with pytest.raises(check_toolchain.ToolchainError, match="exact name==version"):
        check_toolchain.parse_manifest(manifest)


def test_manifest_rejects_lock_generation_command_drift(tmp_path: Path) -> None:
    manifest = (PROJECT_ROOT / "requirements/toolchain.txt").read_text(encoding="utf-8")
    path = tmp_path / "toolchain.txt"
    path.write_text(manifest.replace("--universal", "--no-universal", 1), encoding="utf-8")

    with pytest.raises(check_toolchain.ToolchainError, match="lock generation command"):
        check_toolchain.parse_manifest(path)


def test_project_rejects_tool_pin_drift(tmp_path: Path) -> None:
    manifest = check_toolchain.parse_manifest(PROJECT_ROOT / "requirements/toolchain.txt")
    project = (PROJECT_ROOT / "pyproject.toml").read_text(encoding="utf-8")
    (tmp_path / "pyproject.toml").write_text(
        project.replace('"pytest==9.1.1"', '"pytest>=9.1"'), encoding="utf-8"
    )

    with pytest.raises(check_toolchain.ToolchainError, match="non-exact"):
        check_toolchain.validate_project(tmp_path / "pyproject.toml", manifest)


def test_lock_rejects_generation_command_drift(tmp_path: Path) -> None:
    lock = (PROJECT_ROOT / "requirements/toolchain.lock").read_text(encoding="utf-8")
    path = tmp_path / "toolchain.lock"
    path.write_text(lock.replace("--universal", "--no-universal", 1), encoding="utf-8")
    direct = check_toolchain.parse_manifest(PROJECT_ROOT / "requirements/toolchain.txt")

    with pytest.raises(check_toolchain.ToolchainError, match="generation command"):
        check_toolchain.parse_lock(path, direct)


def test_lock_rejects_unhashed_or_drifted_direct_requirement(tmp_path: Path) -> None:
    header = (
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv pip compile requirements/toolchain.txt --universal --generate-hashes "
        "--python-version 3.11 --output-file requirements/toolchain.lock\n"
    )
    path = tmp_path / "toolchain.lock"
    path.write_text(header + "pytest==9.1.0 \\\n", encoding="utf-8")

    with pytest.raises(check_toolchain.ToolchainError, match="no SHA-256 hash"):
        check_toolchain.parse_lock(path, {"pytest": "9.1.1"})

    path.write_text(
        header
        + "colorama==0.4.6 ; python_full_version < '1' \\\n"
        + "    --hash=sha256:"
        + "a" * 64
        + "\npytest==9.1.0 \\\n"
        + "    --hash=sha256:"
        + "b" * 64
        + "\n",
        encoding="utf-8",
    )
    with pytest.raises(check_toolchain.ToolchainError, match="pytest==9.1.1"):
        check_toolchain.parse_lock(path, {"pytest": "9.1.1"})


def test_installed_verification_reports_missing_or_wrong_versions(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    def version(name: str) -> str:
        if name == "build":
            return "0.0"
        if name == "twine":
            raise importlib.metadata.PackageNotFoundError(name)
        return "1.0"

    monkeypatch.setattr(importlib.metadata, "version", version)

    with pytest.raises(check_toolchain.ToolchainError, match="build: 0.0.*twine: missing"):
        check_toolchain.installed_versions({"build": "1.5.0", "twine": "6.2.0"})


def test_installed_lock_verification_applies_environment_markers(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    header = (
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv pip compile requirements/toolchain.txt --universal --generate-hashes "
        "--python-version 3.11 --output-file requirements/toolchain.lock\n"
    )
    lock = tmp_path / "toolchain.lock"
    lock.write_text(
        header
        + "colorama==0.4.6 ; python_full_version < '1' \\\n"
        + "    --hash=sha256:"
        + "a" * 64
        + "\npytest==9.1.1 \\\n"
        + "    --hash=sha256:"
        + "b" * 64
        + "\n",
        encoding="utf-8",
    )

    def version(name: str) -> str:
        assert name == "pytest"
        return "9.1.1"

    monkeypatch.setattr(importlib.metadata, "version", version)

    assert check_toolchain.installed_lock_versions(lock, {"pytest": "9.1.1"}) == {"pytest": "9.1.1"}
