"""Validate the exact direct build, test, and release tool manifest."""

from __future__ import annotations

import argparse
import importlib.metadata
import re
import tomllib
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import NoReturn, cast

from packaging.markers import Marker

_REQUIREMENT = re.compile(r"([A-Za-z0-9][A-Za-z0-9._-]*)==([A-Za-z0-9][A-Za-z0-9.!+_-]*)")
_LOCKED_REQUIREMENT = re.compile(
    r"([A-Za-z0-9][A-Za-z0-9._-]*)==([A-Za-z0-9][A-Za-z0-9.!+_-]*)"
    r"(?:\s+;\s+([^\\]+?))?\s+\\"
)
_LOCK_HASH = re.compile(r"--hash=sha256:[0-9a-f]{64}(?:\s+\\)?")
_LOCK_COMMAND = (
    "uv pip compile requirements/toolchain.txt --universal --generate-hashes "
    "--python-version 3.11 --output-file requirements/toolchain.lock"
)
_EXPECTED_TOOLS = frozenset(
    {
        "build",
        "coverage",
        "editables",
        "hatchling",
        "hypothesis",
        "joblib",
        "mypy",
        "packaging",
        "pip",
        "pytest",
        "pytest-cov",
        "pytest-xdist",
        "ruff",
        "twine",
        "uv",
    }
)
_OPTIONAL_GROUPS = {
    "dev": frozenset(
        {
            "coverage",
            "hypothesis",
            "joblib",
            "mypy",
            "packaging",
            "pytest",
            "pytest-cov",
            "pytest-xdist",
            "ruff",
        }
    ),
    "bench": frozenset({"joblib"}),
    "release": frozenset({"build", "hatchling", "twine"}),
}


class ToolchainError(ValueError):
    """The direct toolchain manifest or installed environment is inconsistent."""


@dataclass(frozen=True)
class LockedRequirement:
    """One hash-verified version fork and its environment marker."""

    name: str
    version: str
    marker: str | None


def _reject(message: str) -> NoReturn:
    raise ToolchainError(message)


def _normalized_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).casefold()


def parse_manifest(path: Path) -> dict[str, str]:
    """Parse the deliberately narrow exact-version requirements format."""
    lines = path.read_text(encoding="utf-8").splitlines()
    if f"# {_LOCK_COMMAND}" not in lines:
        _reject(f"{path}: direct manifest must record the exact lock generation command")
    tools: dict[str, str] = {}
    for number, raw_line in enumerate(lines, 1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        match = _REQUIREMENT.fullmatch(line)
        if match is None:
            _reject(f"{path}:{number}: expected one exact name==version requirement")
        name, version = match.groups()
        normalized = _normalized_name(name)
        if normalized in tools:
            _reject(f"{path}:{number}: duplicate tool requirement: {normalized}")
        tools[normalized] = version
    observed = frozenset(tools)
    if observed != _EXPECTED_TOOLS:
        missing = ", ".join(sorted(_EXPECTED_TOOLS - observed)) or "none"
        extra = ", ".join(sorted(observed - _EXPECTED_TOOLS)) or "none"
        _reject(f"tool manifest mismatch; missing: {missing}; extra: {extra}")
    return tools


def _lock_entries(path: Path) -> tuple[LockedRequirement, ...]:
    lines = path.read_text(encoding="utf-8").splitlines()
    expected_header = [
        "# This file was autogenerated by uv via the following command:",
        f"#    {_LOCK_COMMAND}",
    ]
    if lines[:2] != expected_header:
        _reject(f"{path}: lock header must contain the exact documented generation command")

    entries: list[LockedRequirement] = []
    current: str | None = None
    current_has_hash = False
    marker_count = 0
    for number, raw_line in enumerate(lines[2:], 3):
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if not raw_line[0].isspace():
            if current is not None and not current_has_hash:
                _reject(f"{path}:{number - 1}: locked requirement has no SHA-256 hash")
            match = _LOCKED_REQUIREMENT.fullmatch(raw_line)
            if match is None:
                _reject(f"{path}:{number}: malformed locked requirement")
            name, version, marker = match.groups()
            current = _normalized_name(name)
            entries.append(
                LockedRequirement(
                    name=current,
                    version=version,
                    marker=None if marker is None else marker.strip(),
                )
            )
            current_has_hash = False
            marker_count += int(" ; " in raw_line)
            continue
        if current is None or _LOCK_HASH.fullmatch(stripped) is None:
            _reject(f"{path}:{number}: expected a SHA-256 hash continuation")
        current_has_hash = True
    if current is not None and not current_has_hash:
        _reject(f"{path}: final locked requirement has no SHA-256 hash")
    if not entries:
        _reject(f"{path}: universal lock must not be empty")
    if marker_count == 0:
        _reject(f"{path}: universal lock must retain platform or Python markers")
    return tuple(entries)


def parse_lock(path: Path, direct_tools: Mapping[str, str]) -> dict[str, frozenset[str]]:
    """Validate the universal compiled lock and return every resolved version."""
    packages: dict[str, set[str]] = {}
    for entry in _lock_entries(path):
        packages.setdefault(entry.name, set()).add(entry.version)
    for name, version in direct_tools.items():
        if packages.get(name) != {version}:
            _reject(f"{path}: direct pin {name}=={version} is absent or forked")
    return {name: frozenset(versions) for name, versions in packages.items()}


def _exact_requirements(values: object, context: str) -> dict[str, str]:
    if not isinstance(values, list) or not all(isinstance(item, str) for item in values):
        _reject(f"{context} must be an array of exact requirements")
    requirements: dict[str, str] = {}
    for raw in cast("list[str]", values):
        match = _REQUIREMENT.fullmatch(raw)
        if match is None:
            _reject(f"{context} contains a non-exact requirement: {raw!r}")
        name, version = match.groups()
        normalized = _normalized_name(name)
        if normalized in requirements:
            _reject(f"{context} contains duplicate requirement: {normalized}")
        requirements[normalized] = version
    return requirements


def validate_project(project_path: Path, tools: Mapping[str, str]) -> None:
    """Require project tool declarations to match the manifest exactly."""
    document = tomllib.loads(project_path.read_text(encoding="utf-8"))
    build_system = document.get("build-system")
    if not isinstance(build_system, dict):
        _reject("pyproject.toml must contain [build-system]")
    build_requirements = _exact_requirements(build_system.get("requires"), "build-system.requires")
    if build_requirements != {"hatchling": tools["hatchling"]}:
        _reject("build-system.requires must exactly match the pinned Hatchling version")

    project = document.get("project")
    if not isinstance(project, dict):
        _reject("pyproject.toml must contain [project]")
    if project.get("dependencies") != []:
        _reject("project.dependencies must remain empty for the zero-runtime-dependency claim")
    optional = project.get("optional-dependencies")
    if not isinstance(optional, dict):
        _reject("pyproject.toml must contain [project.optional-dependencies]")
    for group, expected_names in _OPTIONAL_GROUPS.items():
        requirements = _exact_requirements(optional.get(group), f"optional-dependencies.{group}")
        if frozenset(requirements) != expected_names:
            _reject(f"optional-dependencies.{group} has the wrong direct tool set")
        for name, version in requirements.items():
            if tools[name] != version:
                _reject(
                    f"optional-dependencies.{group} does not match the tool manifest for {name}"
                )


def installed_versions(tools: Mapping[str, str]) -> dict[str, str]:
    """Return installed versions after requiring an exact manifest match."""
    observed: dict[str, str] = {}
    mismatches: list[str] = []
    for name, expected in sorted(tools.items()):
        try:
            actual = importlib.metadata.version(name)
        except importlib.metadata.PackageNotFoundError:
            mismatches.append(f"{name}: missing (expected {expected})")
            continue
        observed[name] = actual
        if actual != expected:
            mismatches.append(f"{name}: {actual} (expected {expected})")
    if mismatches:
        _reject("installed direct toolchain mismatch: " + "; ".join(mismatches))
    return observed


def installed_lock_versions(path: Path, direct_tools: Mapping[str, str]) -> dict[str, str]:
    """Require every active universal-lock entry to be installed exactly."""
    parse_lock(path, direct_tools)
    active: dict[str, str] = {}
    for entry in _lock_entries(path):
        if entry.marker is not None and not Marker(entry.marker).evaluate():
            continue
        previous = active.setdefault(entry.name, entry.version)
        if previous != entry.version:
            _reject(f"active lock forks disagree for {entry.name}: {previous} and {entry.version}")
    observed = installed_versions(active)
    return observed


def validate(root: Path, *, verify_installed: bool) -> dict[str, str]:
    """Validate manifest/project parity and optionally the live environment."""
    tools = parse_manifest(root / "requirements/toolchain.txt")
    lock_path = root / "requirements/toolchain.lock"
    parse_lock(lock_path, tools)
    validate_project(root / "pyproject.toml", tools)
    if verify_installed:
        installed_lock_versions(lock_path, tools)
    return tools


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--verify-installed", action="store_true")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    arguments = _parser().parse_args(argv)
    tools = validate(arguments.root, verify_installed=arguments.verify_installed)
    locked = parse_lock(arguments.root / "requirements/toolchain.lock", tools)
    print(f"direct_tool_pins={len(tools)}")
    print(f"locked_packages={len(locked)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
